version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: freelynk-db
    environment:
      POSTGRES_DB: freelynk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  freelynk-back:
    build: .
    container_name: freelynk-back
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/freelynk
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:
