server:
 error:
  include-message=always
  include-binding-errors=always

spring.application.name=FreeLynk
spring.datasource.url = jdbc:postgresql://localhost:5432/freelynk
spring.datasource.username = postgres
spring.datasource.password = root
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# application.properties (or use env vars)
stripe.secret.key=sk_test_51SFAVK5HvObbxpjgFCh86gTmqTxPUHoxzcGf6Q9xfKTyVHvPgoK9kGnlpR69dBbrF35i9bM7lLJsUnenLYrs9rss00e7aKF5za
# stripe.publishable.key=pk_test_51SFAVK5HvObbxpjgOy8ekmwkGfuP5muwj4OFprcAKzWUqT6JuqySaAYaVFjB99EAk3IwSvlg9JCloVOFIrlQagat00Rpt3HqSy
# stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
# acct_1SFAVK5HvObbxpjg